# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 14:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('type', models.CharField(choices=[('SINGLE', 'SINGLE'), ('MULTI', 'MULTI')], default='MULTI', max_length=10, verbose_name='Тип')),
                ('text', models.TextField(null=True, verbose_name='Описание')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('script', models.FileField(blank=True, upload_to='scripts/', verbose_name='Скрипт')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
