# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='script',
            field=models.FileField(blank=True, upload_to='scripts/', verbose_name='Скрипт'),
        ),
    ]
