drop schema `analytics`;
CREATE SCHEMA `analytics` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE TABLE `analytics`.`events` (
  `idevents` INT NOT NULL AUTO_INCREMENT,
  `android_id` TEXT NULL,
  `app_package_name` TEXT NULL,
  `app_version_name` TEXT NULL,
  `appmetrica_device_id` TEXT NULL,
  `city` TEXT NULL,
  `connection_type` TEXT NULL,
  `country_iso_code` TEXT NULL,
  `device_locale` TEXT NULL,
  `device_manufacturer` TEXT NULL,
  `device_model` TEXT NULL,
  `device_type` TEXT NULL,
  `event_datetime` DATETIME NULL,
  `event_json` text NULL,
  `event_name` TEXT NULL,
  `event_receive_datetime` DATETIME NULL,
  `event_receive_timestamp` TEXT NULL,
  `event_timestamp` TEXT NULL,
  `google_aid` TEXT NULL,
  `ios_ifa` TEXT NULL,
  `ios_ifv` TEXT NULL,
  `mcc` TEXT NULL,
  `mnc` TEXT NULL,
  `operator_name` TEXT NULL,
  `os_name` TEXT NULL,
  `os_version` TEXT NULL,
  PRIMARY KEY (`idevents`));

  CREATE TABLE `analytics`.`errors` (
  `iderror` INT NOT NULL AUTO_INCREMENT,
  `android_id` TEXT NULL,
  `app_package_name` TEXT NULL,
  `app_version_name` TEXT NULL,
  `appmetrica_device_id` TEXT NULL,
  `city` TEXT NULL,
  `connection_type` TEXT NULL,
  `country_iso_code` TEXT NULL,
  `device_locale` TEXT NULL,
  `device_manufacturer` TEXT NULL,
  `device_model` TEXT NULL,
  `device_type` TEXT NULL,
  `error_datetime` DATETIME NULL,
  `error` TEXT NULL,
  `error_id` TEXT NULL,
  `error_receive_datetime` DATETIME NULL,
  `error_receive_timestamp` TEXT NULL,
  `error_timestamp` TEXT NULL,
  `google_aid` TEXT NULL,
  `ios_ifa` TEXT NULL,
  `ios_ifv` TEXT NULL,
  `mcc` TEXT NULL,
  `mnc` TEXT NULL,
  `operator_name` TEXT NULL,
  `os_name` TEXT NULL,
  `os_version` TEXT NULL,
  `windows_aid` TEXT NULL,
  PRIMARY KEY (`iderror`));

  CREATE TABLE `analytics`.`installations` (
  `idinstallation` INT NOT NULL AUTO_INCREMENT,
  `android_id` TEXT NULL,
  `app_package_name` TEXT NULL,
  `app_version_name` TEXT NULL,
  `appmetrica_device_id` TEXT NULL,
  `city` TEXT NULL,
  `connection_type` TEXT NULL,
  `country_iso_code` TEXT NULL,
  `device_locale` TEXT NULL,
  `device_manufacturer` TEXT NULL,
  `device_model` TEXT NULL,
  `device_type` TEXT NULL,
  `match_type` TEXT NULL,
  `is_reinstallation` TEXT NULL,
  `install_receive_timestamp` TEXT NULL,
  `install_timestamp` TEXT NULL,
  `install_ipv6` TEXT NULL,
  `install_datetime` DATETIME NULL,
  `install_receive_datetime` DATETIME NULL,
  `click_datetime` DATETIME NULL,
  `click_ipv6` TEXT NULL,
  `click_id` TEXT NULL,
  `click_user_agent` TEXT NULL,
  `click_url_parameters` TEXT NULL,
  `click_timestamp` TEXT NULL,
  `google_aid` TEXT NULL,
  `ios_ifa` TEXT NULL,
  `ios_ifv` TEXT NULL,
  `mcc` TEXT NULL,
  `mnc` TEXT NULL,
  `operator_name` TEXT NULL,
  `os_name` TEXT NULL,
  `os_version` TEXT NULL,
  `tracking_id` TEXT NULL,
  `tracker_name` TEXT NULL,
  `publisher_name` TEXT NULL,
  `publisher_id` TEXT NULL,
  PRIMARY KEY (`idinstallation`));
  
  
    CREATE TABLE `analytics`.`crashes` (
  `idcrashes` INT NOT NULL AUTO_INCREMENT,
  `android_id` TEXT NULL,
  `app_package_name` TEXT NULL,
  `app_version_name` TEXT NULL,
  `appmetrica_device_id` TEXT NULL,
  `city` TEXT NULL,
  `connection_type` TEXT NULL,
  `country_iso_code` TEXT NULL,
  `crash` TEXT NULL,
  `crash_datetime` DATETIME NULL,
  `crash_group_id` TEXT NULL,
  `crash_id` TEXT NULL,
  `crash_receive_datetime` DATETIME NULL,
  `crash_receive_timestamp` TEXT NULL,
  `crash_timestamp` TEXT NULL,
  `device_locale` TEXT NULL,
  `device_manufacturer` TEXT NULL,
  `device_model` TEXT NULL,
  `device_type` TEXT NULL,
  `google_aid` TEXT NULL,
  `ios_ifa` TEXT NULL,
  `ios_ifv` TEXT NULL,
  `mcc` TEXT NULL,
  `mnc` TEXT NULL,
  `operator_name` TEXT NULL,
  `os_name` TEXT NULL,
  `os_version` TEXT NULL,
  `windows_aid` TEXT NULL,
  PRIMARY KEY (`idcrashes`));
  
