drop schema `analytics`;
CREATE SCHEMA `analytics` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE TABLE `analytics`.`events` (
  `idevents` INT NOT NULL AUTO_INCREMENT,
  `android_id` VARCHAR(1000) NULL,
  `app_package_name` VARCHAR(1000) NULL,
  `app_version_name` VARCHAR(1000) NULL,
  `appmetrica_device_id` VARCHAR(1000) NULL,
  `city` VARCHAR(1000) NULL,
  `connection_type` VARCHAR(1000) NULL,
  `country_iso_code` VARCHAR(1000) NULL,
  `device_locale` VARCHAR(1000) NULL,
  `device_manufacturer` VARCHAR(1000) NULL,
  `device_model` VARCHAR(1000) NULL,
  `device_type` VARCHAR(1000) NULL,
  `event_datetime` DATETIME NULL,
  `event_json` VARCHAR(1000) NULL,
  `event_name` VARCHAR(1000) NULL,
  `event_receive_datetime` DATETIME NULL,
  `event_receive_timestamp` INT(254) NULL,
  `event_timestamp` VARCHAR(1000) NULL,
  `google_aid` VARCHAR(1000) NULL,
  `ios_ifa` VARCHAR(1000) NULL,
  `ios_ifv` VARCHAR(1000) NULL,
  `mcc` INT(254) NULL,
  `mnc` INT(254) NULL,
  `operator_name` VARCHAR(1000) NULL,
  `os_name` VARCHAR(1000) NULL,
  `os_version` VARCHAR(1000) NULL,
  PRIMARY KEY (`idevents`));

  CREATE TABLE `analytics`.`errors` (
  `iderror` INT NOT NULL AUTO_INCREMENT,
  `android_id` VARCHAR(500) NULL,
  `app_package_name` VARCHAR(500) NULL,
  `app_version_name` VARCHAR(500) NULL,
  `appmetrica_device_id` VARCHAR(500) NULL,
  `city` VARCHAR(500) NULL,
  `connection_type` VARCHAR(500) NULL,
  `country_iso_code` VARCHAR(500) NULL,
  `device_locale` VARCHAR(500) NULL,
  `device_manufacturer` VARCHAR(500) NULL,
  `device_model` VARCHAR(500) NULL,
  `device_type` VARCHAR(500) NULL,
  `error_datetime` DATETIME NULL,
  `error` VARCHAR(13000) NULL,
  `error_id` VARCHAR(500) NULL,
  `error_receive_datetime` DATETIME NULL,
  `error_receive_timestamp` INT(254) NULL,
  `error_timestamp` VARCHAR(500) NULL,
  `google_aid` VARCHAR(200) NULL,
  `ios_ifa` VARCHAR(50) NULL,
  `ios_ifv` VARCHAR(50) NULL,
  `mcc` INT(10) NULL,
  `mnc` INT(10) NULL,
  `operator_name` VARCHAR(50) NULL,
  `os_name` VARCHAR(50) NULL,
  `os_version` VARCHAR(50) NULL,
  `windows_aid` VARCHAR(50) NULL,
  PRIMARY KEY (`iderror`));

  CREATE TABLE `analytics`.`installations` (
  `idinstallation` INT NOT NULL AUTO_INCREMENT,
  `android_id` VARCHAR(500) NULL,
  `app_package_name` VARCHAR(500) NULL,
  `app_version_name` VARCHAR(500) NULL,
  `appmetrica_device_id` VARCHAR(500) NULL,
  `city` VARCHAR(500) NULL,
  `connection_type` VARCHAR(500) NULL,
  `country_iso_code` VARCHAR(500) NULL,
  `device_locale` VARCHAR(500) NULL,
  `device_manufacturer` VARCHAR(500) NULL,
  `device_model` VARCHAR(500) NULL,
  `device_type` VARCHAR(500) NULL,
  `match_type` VARCHAR(500) NULL,
  `is_reinstallation` VARCHAR(500) NULL,
  `install_receive_timestamp` VARCHAR(500) NULL,
  `install_timestamp` VARCHAR(500) NULL,
  `install_ipv6` VARCHAR(500) NULL,
  `install_datetime` DATETIME NULL,
  `install_receive_datetime` DATETIME NULL,
  `click_datetime` DATETIME NULL,
  `click_ipv6` VARCHAR(500) NULL,
  `click_id` VARCHAR(500) NULL,
  `click_user_agent` VARCHAR(500) NULL,
  `click_url_parameters` VARCHAR(500) NULL,
  `click_timestamp` VARCHAR(500) NULL,
  `google_aid` VARCHAR(500) NULL,
  `ios_ifa` VARCHAR(500) NULL,
  `ios_ifv` VARCHAR(500) NULL,
  `mcc` INT(254) NULL,
  `mnc` INT(254) NULL,
  `operator_name` VARCHAR(500) NULL,
  `os_name` VARCHAR(500) NULL,
  `os_version` VARCHAR(500) NULL,
  `tracking_id` INT(254) NULL,
  `tracker_name` VARCHAR(500) NULL,
  `publisher_name` VARCHAR(500) NULL,
  `publisher_id` INT(254) NULL,
  PRIMARY KEY (`idinstallation`));
  
  
    CREATE TABLE `analytics`.`crashes` (
  `idcrashes` INT NOT NULL AUTO_INCREMENT,
  `android_id` VARCHAR(500) NULL,
  `app_package_name` VARCHAR(500) NULL,
  `app_version_name` VARCHAR(500) NULL,
  `appmetrica_device_id` VARCHAR(1000) NULL,
  `city` VARCHAR(1000) NULL,
  `connection_type` VARCHAR(1000) NULL,
  `country_iso_code` VARCHAR(1000) NULL,
  `crash` VARCHAR(3000) NULL,
  `crash_datetime` DATETIME NULL,
  `crash_group_id` VARCHAR(1000) NULL,
  `crash_id` VARCHAR(1000) NULL,
  `crash_receive_datetime` DATETIME NULL,
  `crash_receive_timestamp` int(254) NULL,
  `crash_timestamp` int(254) NULL,
  `device_locale` VARCHAR(1000) NULL,
  `device_manufacturer` VARCHAR(1000) NULL,
  `device_model` VARCHAR(1000) NULL,
  `device_type` VARCHAR(1000) NULL,
  `google_aid` VARCHAR(1000) NULL,
  `ios_ifa` VARCHAR(1000) NULL,
  `ios_ifv` VARCHAR(1000) NULL,
  `mcc` INT(254) NULL,
  `mnc` INT(254) NULL,
  `operator_name` VARCHAR(1000) NULL,
  `os_name` VARCHAR(500) NULL,
  `os_version` VARCHAR(500) NULL,
  `windows_aid` VARCHAR(500) NULL,
  PRIMARY KEY (`idcrashes`));
  
